const nationalParks = [
 {
   "parkName": "Death Valley",
   "state": ["California", "Nevada"],
   "dateEstablished": "October 31, 1994",
   "latitude": "36.24°N",
   "longitude": "116.82°W",
   "annualVisitors": 1294827,
   "websiteUrl": "https://www.nps.gov/deva/index.htm",
   "urlCode": "deva",
   "image": "assets/death-valley.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://sites.google.com/site/thebrockeninglory/\">Brocken Inaglory</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=5990426\">Link</a>",
   "sizeAcres": 337306314,
   "description": "The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies. The White River Badlands contain the largest assemblage of known late Eocene and Oligocene mammal fossils. The wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs."
 },
 {
   "parkName": "Great Smoky Mountains",
   "state": ["Tennessee", "North Carolina"],
   "dateEstablished": "June 15, 1934",
   "latitude": "35.68°N",
   "longitude": "83.53°W",
   "annualVisitors": 11338893,
   "websiteUrl": "https://www.nps.gov/grsm/index.htm",
   "urlCode": "grsm",
   "image": "assets/great-smoky-mtns.jpeg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Blinutne\" title=\"User:Blinutne\">Blinutne</a>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2518140\">Link</a>",
   "sizeAcres": 52242688,
   "description": "The Great Smoky Mountains, part of the Appalachian Mountains, span a wide range of elevations, making them home to over 400 vertebrate species, 100 tree species, and 5000 plant species. Hiking is the park\\'s main attraction, with over 800 miles (1,300 km) of trails, including 70 miles (110 km) of the Appalachian Trail. Other activities include fishing, horseback riding, and touring nearly 80 historic structures."
 },
 {
   "parkName": "Yellowstone",
   "state": ["Wyoming", "Montana", "Idaho"],
   "dateEstablished": "March 1, 1872",
   "latitude": "44.60°N",
   "longitude": "110.50°W",
   "annualVisitors": 4116524,
   "websiteUrl": "https://www.nps.gov/yell/index.htm",
   "urlCode": "yell",
   "image": "assets/yellowstone.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://sites.google.com/site/thebrockeninglory/\">Brocken Inaglory</a>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=6051164\">Link</a>",
   "sizeAcres": 221979071,
   "description": "Situated on the Yellowstone Caldera, the park has an expansive network of geothermal areas including boiling mud pots, vividly colored hot springs such as Grand Prismatic Spring, and regularly erupting geysers, the best-known being Old Faithful. The yellow-hued Grand Canyon of the Yellowstone River contains several high waterfalls, and four mountain ranges traverse the park. More than 60 mammal species including gray wolves, grizzly bears, black bears, lynxes, bison, and elk, make this park one of the best wildlife viewing spots in the country."
 },
 {
   "parkName": "Denali",
   "state": "Alaska",
   "dateEstablished": "February 26, 1917",
   "latitude": "63.33°N",
   "longitude": "150.50°W",
   "annualVisitors": 642809,
   "websiteUrl": "https://www.nps.gov/dena/index.htm",
   "urlCode": "dena",
   "image": "assets/denali.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Ram-Man\" class=\"extiw\" title=\"en:User:Ram-Man\">Ram-Man</a>) - <span class=\"int-own-work\">Self-photographed</span>, <a href=\"http://www.gnu.org/licenses/old-licenses/fdl-1.2.html\" title=\"GNU Free Documentation License 1.2\">GFDL 1.2</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1077736\">Link</a>",
   "sizeAcres": 474091116,
   "description": "Centered on Denali, the tallest mountain in North America, Denali is serviced by a single road leading to Wonder Lake. Denali and other peaks of the Alaska Range are covered with long glaciers and boreal forest. Wildlife includes grizzly bears, Dall sheep, caribou, and gray wolves."
 },
 {
   "parkName": "Gates of the Arctic",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "67.78°N",
   "longitude": "153.30°W",
   "annualVisitors": 11177,
   "websiteUrl": "https://www.nps.gov/gaar/index.htm",
   "urlCode": "gaar",
   "image": "assets/gates-of-arctic.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/File:USFWS_alt_graphic_A.svg\" class=\"image\"></a>This image originates from the <a rel=\"nofollow\" class=\"external text\" href=\"http://digitalmedia.fws.gov/cdm/\">National Digital Library</a> of the <a href=\"https://en.wikipedia.org/wiki/United_States_Fish_and_Wildlife_Service\" class=\"extiw\" title=\"w:United States Fish and Wildlife Service\">United States Fish and Wildlife Service</a>at <a rel=\"nofollow\" class=\"external text\" href=\"http://digitalmedia.fws.gov/cdm/singleitem/collection/natdiglib/id/3957/rec/1\">this page</a>This tag does not indicate the copyright status of the attached work. A normal <a href=\"//commons.wikimedia.org/wiki/Special:MyLanguage/Commons:Copyright_tags\" title=\"Special:MyLanguage/Commons:Copyright tags\">copyright tag</a> is still required. See <a href=\"//commons.wikimedia.org/wiki/Special:MyLanguage/Commons:Licensing\" title=\"Special:MyLanguage/Commons:Licensing\">Commons:Licensing</a> for more information.See <a href=\"//commons.wikimedia.org/wiki/Category:Images_from_the_United_States_Fish_and_Wildlife_Service\" title=\"Category:Images from the United States Fish and Wildlife Service\">Category:Images from the United States Fish and Wildlife Service</a>.Transferred from <span class=\"plainlinks\"><a class=\"external text\" href=\"//en.wikipedia.org\">en.wikipedia</a></span> to Commons by <a href=\"//commons.wikimedia.org/wiki/User:Aconcagua\" title=\"User:Aconcagua\">Aconcagua</a> using <a href=\"https://tools.wmflabs.org/commonshelper/\" class=\"extiw\" title=\"toollabs:commonshelper/\">CommonsHelper</a>.Source: SL-02192URL: <a rel=\"nofollow\" class=\"external free\" href=\"https://digitalmedia.fws.gov/digital/collection/natdiglib/id/3957/rec/1\">https://digitalmedia.fws.gov/digital/collection/natdiglib/id/3957/rec/1</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=4495169\">Link</a>",
   "sizeAcres": 752389745,
   "description": "The country\\'s northernmost park protects an expanse of pure wilderness in Alaska\\'s Brooks Range and has no park facilities. The land is home to Alaska Natives who have relied on the land and caribou for 11,000 years."
 },
 {
   "parkName": "Glacier Bay",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "58.50°N",
   "longitude": "137.00°W",
   "annualVisitors": 547057,
   "websiteUrl": "https://www.nps.gov/glba/index.htm",
   "urlCode": "glba",
   "image": "assets/glacier-bay.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Janquen\" class=\"extiw\" title=\"en:User:Janquen\">Janquen</a> at the <a href=\"https://en.wikipedia.org/wiki/\" class=\"extiw\" title=\"w:\">English language Wikipedia</a>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=6308223\">Link</a>",
   "sizeAcres": 322338343,
   "description": "Glacier Bay contains tidewater glaciers, mountains, fjords, and a temperate rainforest, and is home to large populations of grizzly bears, mountain goats, whales, seals, and eagles. When discovered in 1794 by George Vancouver, the entire bay was covered by ice, but the glaciers have since receded more than 65 miles (105 km)."
 },
 {
   "parkName": "Katmai",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "58.50°N",
   "longitude": "155.00°W",
   "annualVisitors": 37818,
   "websiteUrl": "https://www.nps.gov/katm/index.htm",
   "urlCode": "katm",
   "image": "assets/katmai.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Mbz1\" title=\"User:Mbz1\">Mbz1</a> assumed (based on copyright claims). - No machine-readable source provided. Own work assumed (based on copyright claims)., <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1976603\">Link</a>",
   "sizeAcres": 367452933,
   "description": "This park on the Alaska Peninsula protects the Valley of Ten Thousand Smokes, an ash flow formed by the 1912 eruption of Novarupta, as well as Mount Katmai. Over 2,000 grizzly bears come here each year to catch spawning salmon. Other wildlife includes caribou, wolves, moose, and wolverines."
 },
 {
   "parkName": "Kenai Fjords",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "59.92°N",
   "longitude": "149.65°W",
   "annualVisitors": 303598,
   "websiteUrl": "https://www.nps.gov/kefj/index.htm",
   "urlCode": "kefj",
   "image": "assets/kenai-fjords.jpeg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Reywas92\" title=\"User:Reywas92\">Reywas92</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=8949763\">Link</a>",
   "sizeAcres": 66965005,
   "description": "Near Seward on the Kenai Peninsula, this park protects the Harding Icefield and at least 38 glaciers and fjords stemming from it. The only area accessible to the public by road is Exit Glacier; the rest must be viewed or reached from boat tours."
 },
 {
   "parkName": "Kobuk Valley",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "67.55°N",
   "longitude": "159.28°W",
   "annualVisitors": 15500,
   "websiteUrl": "https://www.nps.gov/kova/index.htm",
   "urlCode": "kova",
   "image": "assets/kobuk.jpg",
   "imageRef": "<a href=\"https://www.nps.gov/kova/learn/nature/great-kobuk-sand-dunes.htm\">National Park Service</a>",
   "sizeAcres": 175071616,
   "description": "Kobuk Valley protects 61 miles (98 km) of the Kobuk River and three regions of sand dunes. Created by glaciers, the Great Kobuk, Little Kobuk, and Hunt River Sand Dunes can reach 100 feet (30 m) high and 100 °F (38 °C), and they are the largest dunes in the Arctic. Twice a year, half a million caribou migrate through the dunes and across river bluffs that expose well-preserved ice age fossils."
 },
 {
   "parkName": "Lake Clark",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "60.97°N",
   "longitude": "153.42°W",
   "annualVisitors": 22755,
   "websiteUrl": "https://www.nps.gov/lacl/index.htm",
   "urlCode": "lacl",
   "image": "assets/lake-clark.jpg",
   "imageRef": "<a href=\"https://commons.wikimedia.org/w/index.php?curid=317919\">Link</a>",
   "sizeAcres": 261981649,
   "description": "The region around Lake Clark features four active volcanoes, including Mount Redoubt, as well as an abundance of rivers, glaciers, and waterfalls. Temperate rainforests, a tundra plateau, and three mountain ranges complete the landscape."
 },
 {
   "parkName": "Wrangell - St. Elias",
   "state": "Alaska",
   "dateEstablished": "December 2, 1980",
   "latitude": "61.00°N",
   "longitude": "142.00°W",
   "annualVisitors": 68292,
   "websiteUrl": "https://www.nps.gov/wrst/index.htm",
   "urlCode": "wrst",
   "image": "assets/wrangell.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external free\" href=\"http://pubs.usgs.gov/dds/dds-39/\">http://pubs.usgs.gov/dds/dds-39/</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1982495\">Link</a>",
   "sizeAcres": 832314648,
   "description": "An over 8 million acres (32,375 km2) plot of mountainous country—the largest national park in the system—protects the convergence of the Alaska, Chugach, and Wrangell-Saint Elias Ranges, which include many of the continent\\'s tallest mountains and volcanoes, including the 18,008-foot Mount Saint Elias. More than a quarter of the park is covered with glaciers, including the tidewater Hubbard Glacier, piedmont Malaspina Glacier, and valley Nabesna Glacier."
 },
 {
   "parkName": "American Samoa",
   "state": "American Samoa",
   "dateEstablished": "October 31, 1988",
   "latitude": "14.25°S",
   "longitude": "170.68°W",
   "annualVisitors": 69468,
   "websiteUrl": "https://www.nps.gov/npsa/index.htm",
   "urlCode": "npsa",
   "image": "assets/american-samoa.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"http://www.nps.gov/npsa/photosmultimedia/index%2Ehtm?eid=104832&amp;root_aId=33#e_104832\">NPS Sea and Landscapes Photo Gallery</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=6729753\">Link</a>",
   "sizeAcres": 825667,
   "description": "The southernmost national park is on three Samoan islands and protects coral reefs, rainforests, volcanic mountains, and white beaches. The area is also home to flying foxes, brown boobies, sea turtles, and 900 species of fish."
 },
 {
   "parkName": "Grand Canyon",
   "state": "Arizona",
   "dateEstablished": "February 26, 1919",
   "latitude": "36.06°N",
   "longitude": "112.14°W",
   "annualVisitors": 6254238,
   "websiteUrl": "https://www.nps.gov/grca/index.htm",
   "urlCode": "grca",
   "image": "assets/grand-canyon.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Lucag\" title=\"User:Lucag\">Luca Galuzzi</a>, <a href=\"https://creativecommons.org/licenses/by-sa/2.5\" title=\"Creative Commons Attribution-Share Alike 2.5\">CC BY-SA 2.5</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2689200\">Link</a>",
   "sizeAcres": 120164703,
   "description": "The Grand Canyon, carved by the mighty Colorado River, is 277 miles (446 km) long, up to 1 mile (1.6 km) deep, and up to 15 miles (24 km) wide. Millions of years of erosion have exposed the multicolored layers of the Colorado Plateau in mesas and canyon walls, visible from both the north and south rims, or from a number of trails that descend into the canyon itself."
 },
 {
   "parkName": "Petrified Forest",
   "state": "Arizona",
   "dateEstablished": "December 9, 1962",
   "latitude": "35.07°N",
   "longitude": "109.78°W",
   "annualVisitors": 627757,
   "websiteUrl": "https://www.nps.gov/pefo/index.htm",
   "urlCode": "pefo",
   "image": "assets/petrified-forest.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Doug_Dolde\" class=\"extiw\" title=\"wikipedia:User:Doug Dolde\">Doug Dolde</a> at <a href=\"https://en.wikipedia.org/wiki/\" class=\"extiw\" title=\"wikipedia:\">English Wikipedia</a> - Transferred from <span class=\"plainlinks\"><a class=\"external text\" href=\"//en.wikipedia.org\">en.wikipedia</a></span> to Commons by <a href=\"//commons.wikimedia.org/wiki/User:Dmitri_Lytov\" title=\"User:Dmitri Lytov\">Dmitri Lytov</a> using <a href=\"https://tools.wmflabs.org/commonshelper/\" class=\"extiw\" title=\"toollabs:commonshelper/\">CommonsHelper</a>., Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=7209006\">Link</a>",
   "sizeAcres": 22139021,
   "description": "This portion of the Chinle Formation has a large concentration of 225-million-year-old petrified wood. The surrounding Painted Desertfeatures eroded cliffs of red-hued volcanic rock called bentonite. Dinosaur fossils and over 350 Native American sites are also protected in this park."
 },
 {
   "parkName": "Saguaro",
   "state": "Arizona",
   "dateEstablished": "October 14, 1994",
   "latitude": "32.25°N",
   "longitude": "110.50°W",
   "annualVisitors": 964760,
   "websiteUrl": "https://www.nps.gov/sagu/index.htm",
   "urlCode": "sagu",
   "image": "assets/saguaro.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/people/23642145@N00\">Luke Jones</a> from Yucca Valley - <a rel=\"nofollow\" class=\"external free\" href=\"https://www.flickr.com/photos/23642145@N00/2972546483/\">https://www.flickr.com/photos/23642145@N00/2972546483/</a>, <a href=\"https://creativecommons.org/licenses/by/2.0\" title=\"Creative Commons Attribution 2.0\">CC BY 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=8482937\">Link</a>",
   "sizeAcres": 9171572,
   "description": "Split into the separate Rincon Mountain and Tucson Mountaindistricts, this park is evidence that the dry Sonoran Desert is still home to a great variety of life spanning six biotic communities. Beyond the namesake giant saguaro cacti, there are barrel cacti, chollas, and prickly pears, as well as lesser long-nosed bats, spotted owls, and javelinas."
 },
 {
   "parkName": "Hot Springs",
   "state": "Arkansas",
   "dateEstablished": "March 4, 1921",
   "latitude": "34.51°N",
   "longitude": "93.05°W",
   "annualVisitors": 1561616,
   "websiteUrl": "https://www.nps.gov/hosp/index.htm",
   "urlCode": "hosp",
   "image": "assets/hot-springs.jpg",
   "imageRef": "<a href=\"https://www.nps.gov/hosp/index.htm\">National Park Service</a>",
   "sizeAcres": 554801,
   "description": "Hot Springs was established as a federal reserve by Congress on April 20, 1832—the oldest area managed by the National Park Service. Congress redesignated Hot Springs as a national park on March 4, 1921. Natural hot springs flow out of the Ouachita Mountains, providing opportunities for relaxation in a historic setting. Bathhouse Row preserves numerous examples of 19th-century architecture. Hot Springs is the first national park in a city and was the smallest national park until February 22, 2018 when the Jefferson National Expansion Memorial was redesignated Gateway Arch National Park."
 },
 {
   "parkName": "Channel Islands",
   "state": "California",
   "dateEstablished": "March 5, 1980",
   "latitude": "34.01°N",
   "longitude": "119.42°W",
   "annualVisitors": 383687,
   "websiteUrl": "https://www.nps.gov/chis/index.htm",
   "urlCode": "chis",
   "image": "assets/channel-islands.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Rmhermen\" class=\"extiw\" title=\"wikipedia:User:Rmhermen\">Rmhermen</a> at <a href=\"https://en.wikipedia.org/wiki/\" class=\"extiw\" title=\"wikipedia:\">English Wikipedia</a>. - Transferred from <span class=\"plainlinks\"><a class=\"external text\" href=\"//en.wikipedia.org\">en.wikipedia</a></span> to Commons., Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=3451089\">Link</a>",
   "sizeAcres": 24956100,
   "description": "Five of the eight Channel Islands are protected, and half of the park\\'s area is underwater. The islands have a unique Mediterranean ecosystem originally settled by the Chumash people. They are home to over 2,000 species of land plants and animals, and 145 are unique to them, including the island fox. Ferry services offer transportation to the islands from the mainland."
 },
 {
   "parkName": "Joshua Tree",
   "state": "California",
   "dateEstablished": "October 31, 1994",
   "latitude": "33.79°N",
   "longitude": "115.90°W",
   "annualVisitors": 2853619,
   "websiteUrl": "https://www.nps.gov/jotr/index.htm",
   "urlCode": "jotr",
   "image": "assets/joshua-tree.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Jarekt\" title=\"User:Jarekt\">Jarek Tuszyński</a> / CC-BY-SA-3.0 &amp; GDFL, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=7265775\">Link</a>",
   "sizeAcres": 79063574,
   "description": "Covering large areas of the Colorado and Mojave Deserts and the Little San Bernardino Mountains, this desert landscape is populated by vast stands of Joshua trees. Large changes in elevation reveal various contrasting environments including bleached sand dunes, dry lakes, rugged mountains, and maze-like clusters of monzogranitemonoliths."
 },
 {
   "parkName": "Kings Canyon",
   "state": "California",
   "dateEstablished": "March 4, 1940",
   "latitude": "36.80°N",
   "longitude": "118.55°W",
   "annualVisitors": 692932,
   "websiteUrl": "https://www.nps.gov/seki/index.htm",
   "urlCode": "seki",
   "image": "assets/kings-canyon.jpeg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:Crd637&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:Crd637 (page does not exist)\">Crd637</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=20032656\">Link</a>",
   "sizeAcres": 46190120,
   "description": "Home to several giant sequoia groves and the General Grant Tree, the world\\'s second largest measured tree, this park also features part of the Kings River, sculptor of the dramatic granite canyon that is its namesake, and the San Joaquin River, as well as Boyden Cave. Although Kings Canyon National Park was designated as such in 1940, it subsumed General Grant National Park, which had been established on October 1, 1890 as the United States\\' fourth national park."
 },
 {
   "parkName": "Lassen Volcanic",
   "state": "California",
   "dateEstablished": "August 9, 1916",
   "latitude": "40.49°N",
   "longitude": "121.51°W",
   "annualVisitors": 507256,
   "websiteUrl": "https://www.nps.gov/lavo/index.htm",
   "urlCode": "lavo",
   "image": "assets/lassen-volcanic.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/people/34450190@N08\">Joe Parks</a> from Berkeley, CA - <a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/photos/parksjd/7744407908/\">Lake Helen</a>, <a href=\"https://creativecommons.org/licenses/by/2.0\" title=\"Creative Commons Attribution 2.0\">CC BY 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=26554063\">Link</a>",
   "sizeAcres": 10658902,
   "description": "Lassen Peak, the largest lava dome volcano in the world, is joined by all three other types of volcanoes in this park: shield, cinder cone, and composite. Though Lassen itself last erupted in 1915, most of the rest of the park is continuously active. Numerous hydrothermal features, including fumaroles, boiling pools, and bubbling mud pots, are heated by molten rock from beneath the peak."
 },
 {
   "parkName": "Pinnacles",
   "state": "California",
   "dateEstablished": "January 10, 2013",
   "latitude": "36.48°N",
   "longitude": "121.16°W",
   "annualVisitors": 233334,
   "websiteUrl": "https://www.nps.gov/pinn/index.htm",
   "urlCode": "pinn",
   "image": "assets/pinnacles.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:Samartur&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:Samartur (page does not exist)\">Samartur</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=32162401\">Link</a>",
   "sizeAcres": 2668573,
   "description": "Named for the eroded leftovers of a portion of an extinct volcano, the park\\'s massive black and gold monoliths of andesite and rhyolite are a popular destination for rock climbers. Hikers have access to trails crossing the Coast Range wilderness. The park is home to the endangered California condor (Gymnogyps californianus) and one of the few locations in the world where these extremely rare birds can be seen in the wild. Pinnacles also supports a dense population of prairie falcons, and more than 13 species of bat which populate its talus caves."
 },
 {
   "parkName": "Redwood",
   "state": "California",
   "dateEstablished": "October 2, 1968",
   "latitude": "41.30°N",
   "longitude": "124.00°W",
   "annualVisitors": 445000,
   "websiteUrl": "https://www.nps.gov/redw/index.htm",
   "urlCode": "redw",
   "image": "assets/redwood.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external free\" href=\"https://www.flickr.com/photos/schweppe/21556590/\">https://www.flickr.com/photos/schweppe/21556590/</a>, <a href=\"https://creativecommons.org/licenses/by-sa/2.0\" title=\"Creative Commons Attribution-Share Alike 2.0\">CC BY-SA 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=4049158\">Link</a>",
   "sizeAcres": 13899937,
   "description": "This park and the co-managed state parks protect almost half of all remaining coastal redwoods, the tallest trees on earth. There are three large river systems in this very seismically active area, and 37 miles (60 km) of protected coastline reveal tide pools and seastacks. The prairie, estuary, coast, river, and forest ecosystems contain a wide variety of animal and plant species."
 },
 {
   "parkName": "Sequoia",
   "state": "California",
   "dateEstablished": "September 25, 1890",
   "latitude": "36.43°N",
   "longitude": "118.68°W",
   "annualVisitors": 1291256,
   "websiteUrl": "https://www.nps.gov/seki/index.htm",
   "urlCode": "seki",
   "image": "assets/sequoia.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Davigoli\" class=\"extiw\" title=\"en:User:Davigoli\">Davigoli</a> at <a class=\"external text\" href=\"http://en.wikipedia.org\">en.wikipedia</a> - <a class=\"external text\" href=\"http://en.wikipedia.org\">en.wikipedia</a> (photo by Carey Goldstein); transferred to Commons by <a href=\"//commons.wikimedia.org/wiki/User:ThomasPusch\" title=\"User:ThomasPusch\">User:ThomasPusch</a> using <a rel=\"nofollow\" class=\"external text\" href=\"http://tools.wikimedia.de/~magnus/commonshelper.php\">CommonsHelper</a>., Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=5754700\">Link</a>",
   "sizeAcres": 40406263,
   "description": "This park protects the Giant Forest, which boasts some of the world\\'s largest trees, the General Sherman being the largest measured tree in the park. Other features include over 240 caves, a long segment of the Sierra Nevada including the tallest mountain in the contiguous United States, and Moro Rock, a large granite dome."
 },
 {
   "parkName": "Yosemite",
   "state": "California",
   "dateEstablished": "October 1, 1890",
   "latitude": "37.83°N",
   "longitude": "119.50°W",
   "annualVisitors": 4336890,
   "websiteUrl": "https://www.nps.gov/yose/index.htm",
   "urlCode": "yose",
   "image": "assets/yosemite.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:AngMoKio\" title=\"User:AngMoKio\">user:AngMoKio</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span> (<span lang=\"en\">Original text: selfmade photo</span>), <a href=\"https://creativecommons.org/licenses/by-sa/2.5\" title=\"Creative Commons Attribution-Share Alike 2.5\">CC BY-SA 2.5</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2827221\">Link</a>",
   "sizeAcres": 76174750,
   "description": "Yosemite features sheer granite cliffs, exceptionally tall waterfalls, and old-growth forests at a unique intersection of geology and hydrology. Half Dome and El Capitan rise from the park\\'s centerpiece, the glacier-carved Yosemite Valley, and from its vertical walls drop Yosemite Falls, one of North America\\'s tallest waterfalls at 2,425 feet (739 m) high. Three giant sequoia groves, along with a pristine wilderness in the heart of the Sierra Nevada, are home to a wide variety of rare plant and animal species."
 },
 {
   "parkName": "Black Canyon of the Gunnison",
   "state": "Colorado",
   "dateEstablished": "October 21, 1999",
   "latitude": "38.57°N",
   "longitude": "107.72°W",
   "annualVisitors": 307143,
   "websiteUrl": "https://www.nps.gov/blca/index.htm",
   "urlCode": "blca",
   "image": "assets/black-canyon.jpg",
   "imageRef": "<a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=538346\">Link</a>",
   "sizeAcres": 3078076,
   "description": "The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies. The White River Badlands contain the largest assemblage of known late Eocene and Oligocene mammal fossils. The wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs."
 },
 {
   "parkName": "Great Sand Dunes",
   "state": "Colorado",
   "dateEstablished": "September 13, 2004",
   "latitude": "37.73°N",
   "longitude": "105.51°W",
   "annualVisitors": 486935,
   "websiteUrl": "https://www.nps.gov/grsa/index.htm",
   "urlCode": "grsa",
   "image": "assets/great-sand-dunes.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/File:Coloradodunes.jpg\" title=\"Copyrighted free use\">Copyrighted free use</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=62679\">Link</a>",
   "sizeAcres": 10734187,
   "description": "The tallest sand dunes in North America, up to 750 feet (230 m) tall, were formed by deposits of the ancient Rio Grande in the San Luis Valley. Abutting a variety of grasslands, shrublands, and wetlands, the park also has alpine lakes, six 13,000-foot mountains, and old-growth forests."
 },
 {
   "parkName": "Mesa Verde",
   "state": "Colorado",
   "dateEstablished": "June 29, 1906",
   "latitude": "37.18°N",
   "longitude": "108.49°W",
   "annualVisitors": 613788,
   "websiteUrl": "https://www.nps.gov/meve/index.htm",
   "urlCode": "meve",
   "image": "assets/mesa-verde.jpg",
   "imageRef": "<a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=5330611\">Link</a>",
   "sizeAcres": 5248517,
   "description": "This area constitutes over 4,000 archaeological sites of the Ancestral Puebloan people, who lived here and elsewhere in the Four Corners region for at least 700 years. Cliff dwellings built in the 12th and 13th centuries include Cliff Palace, which has 150 rooms and 23 kivas, and the Balcony House, with its many passages and tunnels."
 },
 {
   "parkName": "Rocky Mountain",
   "state": "Colorado",
   "dateEstablished": "January 26, 1915",
   "latitude": "40.40°N",
   "longitude": "105.58°W",
   "annualVisitors": 4437215,
   "websiteUrl": "https://www.nps.gov/romo/index.htm",
   "urlCode": "romo",
   "image": "assets/rocky-mountain.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:K.lee~commonswiki\" title=\"User:K.lee~commonswiki\">K. Lee</a> (<a href=\"//commons.wikimedia.org/wiki/User_talk:K.lee~commonswiki\" title=\"User talk:K.lee~commonswiki\">talk</a><span style=\"white-space:nowrap\">&nbsp;·</span> <a href=\"//commons.wikimedia.org/wiki/Special:Contributions/K.lee~commonswiki\" title=\"Special:Contributions/K.lee~commonswiki\">contribs</a>) - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=833716\">Link</a>",
   "sizeAcres": 26579520,
   "description": "Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m)."
 },
 {
   "parkName": "Biscayne",
   "state": "Florida",
   "dateEstablished": "June 28, 1980",
   "latitude": "25.65°N",
   "longitude": "80.08°W",
   "annualVisitors": 446961,
   "websiteUrl": "https://www.nps.gov/bisc/index.htm",
   "urlCode": "bisc",
   "image": "assets/biscayne.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external free\" href=\"http://www.nps.gov/bisc/photosmultimedia/photogallery.htm?eid=202009&amp;root_aId=164#e_202009\">http://www.nps.gov/bisc/photosmultimedia/photogallery.htm?eid=202009&amp;root_aId=164#e_202009</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=9066936\">Link</a>",
   "sizeAcres": 17297111,
   "description": "Located in Biscayne Bay, this park at the north end of the Florida Keys has four interrelated marine ecosystems: mangrove forest, the Bay, the Keys, and coral reefs. Threatened animals include the West Indian manatee, American crocodile, various sea turtles, and peregrine falcon."
 },
 {
   "parkName": "Dry Tortugas",
   "state": "Florida",
   "dateEstablished": "October 26, 1992",
   "latitude": "24.63°N",
   "longitude": "82.87°W",
   "annualVisitors": 54281,
   "websiteUrl": "https://www.nps.gov/drto/index.htm",
   "urlCode": "drto",
   "image": "assets/dry-tortugas.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external autonumber\" href=\"http://photo.itc.nps.gov/storage/images/drto/drto-Full.00001.html\">[1]</a>; English Wikipedia, original upload 2 March 2005 by <a href=\"https://en.wikipedia.org/wiki/User:Brian0918\" class=\"extiw\" title=\"en:User:Brian0918\">Brian0918</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=326325\">Link</a>",
   "sizeAcres": 6470122,
   "description": "The islands of the Dry Tortugas, at the westernmost end of the Florida Keys, are the site of Fort Jefferson, a Civil War-era fort that is the largest masonry structure in the Western Hemisphere. The park is home to undisturbed coral reefs and shipwrecks, and is only accessible by plane or boat."
 },
 {
   "parkName": "Everglades",
   "state": "Florida",
   "dateEstablished": "May 30, 1934",
   "latitude": "25.32°N",
   "longitude": "80.93°W",
   "annualVisitors": 1018557,
   "websiteUrl": "https://www.nps.gov/ever/index.htm",
   "urlCode": "ever",
   "image": "assets/everglades.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external autonumber\" href=\"http://www.nps.gov/ever/parknews/evergladeshabitatimages.htm\">[1]</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=3632000\">Link</a>",
   "sizeAcres": 150893425,
   "description": "The Everglades are the largest tropical wilderness in the United States. This mangrove and tropical rainforest ecosystem and marine estuary is home to 36 protected species, including the Florida panther, American crocodile, and West Indian manatee. Some areas have been drained and developed; restoration projects aim to restore the ecology."
 },
 {
   "parkName": "Haleakala",
   "state": "Hawaii",
   "dateEstablished": "August 1, 1916",
   "latitude": "20.72°N",
   "longitude": "156.17°W",
   "annualVisitors": 1112390,
   "websiteUrl": "https://www.nps.gov/hale/index.htm",
   "urlCode": "hale",
   "image": "assets/haleakala.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:Matttrain&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:Matttrain (page does not exist)\">Matttrain</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=7101246\">Link</a>",
   "sizeAcres": 3326462,
   "description": "The Haleakalā volcano on Maui features a very large crater with numerous cinder cones, Hosmer\\'s Grove of alien trees, the Kipahulusection\\'s scenic pools of freshwater fish, and the native Hawaiian goose. The park protects the greatest number of endangered species within a U.S. National Park."
 },
 {
   "parkName": "Hawaii Volcanoes",
   "state": "Hawaii",
   "dateEstablished": "August 1, 1916",
   "latitude": "19.38°N",
   "longitude": "155.20°W",
   "annualVisitors": 2016702,
   "websiteUrl": "https://www.nps.gov/havo/index.htm",
   "urlCode": "havo",
   "image": "assets/hawaii-volcanoes.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Hike395\" class=\"extiw\" title=\"en:User:Hike395\">Hike395</a> (<a href=\"https://en.wikipedia.org/wiki/User_talk:Hike395\" class=\"extiw\" title=\"en:User talk:Hike395\">talk</a><span style=\"white-space:nowrap\">&nbsp;·</span> <a href=\"https://en.wikipedia.org/wiki/Special:Contributions/Hike395\" class=\"extiw\" title=\"en:Special:Contributions/Hike395\">contribs</a>) - <a rel=\"nofollow\" class=\"external text\" href=\"http://pubs.usgs.gov/dds/dds-80/images/JPG/large_screen/RIFT_007.jpg\">USGS</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=4412830\">Link</a>",
   "sizeAcres": 32343138,
   "description": "This park on the Big Island protects the Kīlauea and Mauna Loavolcanoes, two of the world\\'s most active geological features. Diverse ecosystems range from tropical forests at sea level to barren lava beds at more than 13,000 feet (4,000 m)."
 },
 {
   "parkName": "Mammoth Cave",
   "state": "Kentucky",
   "dateEstablished": "July 1, 1941",
   "latitude": "37.18°N",
   "longitude": "86.10°W",
   "annualVisitors": 587853,
   "websiteUrl": "https://www.nps.gov/maca/index.htm",
   "urlCode": "maca",
   "image": "assets/mammoth-cave.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external free\" href=\"https://www.flickr.com/photos/navin75/162067155/\">https://www.flickr.com/photos/navin75/162067155/</a>, <a href=\"https://creativecommons.org/licenses/by-sa/2.0\" title=\"Creative Commons Attribution-Share Alike 2.0\">CC BY-SA 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=3676754\">Link</a>",
   "sizeAcres": 5401191,
   "description": "With more than 400 miles (640 km) of passageways explored, Mammoth Cave is the world\\'s longest known cave system. Subterranean wildlife includes eight bat species, Kentucky cave shrimp, Northern cavefish, and cave salamanders. Above ground, the park provides recreation on the Green River, 70 miles of hiking trails, and plenty of sinkholes and springs."
 },
 {
   "parkName": "Acadia",
   "state": "Maine",
   "dateEstablished": "February 26, 1919",
   "latitude": "44.35°N",
   "longitude": "68.21°W",
   "annualVisitors": 3509271,
   "websiteUrl": "https://www.nps.gov/acad/index.htm",
   "urlCode": "acad",
   "image": "assets/acadia.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:FirozAnsari&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:FirozAnsari (page does not exist)\">FirozAnsari</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=62714730\">Link</a>",
   "sizeAcres": 4907526,
   "description": "Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes. There are freshwater, estuary, forest, and intertidal habitats."
 },
 {
   "parkName": "Isle Royale",
   "state": "Michigan",
   "dateEstablished": "April 3, 1940",
   "latitude": "48.10°N",
   "longitude": "88.55°W",
   "annualVisitors": 28196,
   "websiteUrl": "https://www.nps.gov/isro/index.htm",
   "urlCode": "isro",
   "image": "assets/isle-royale.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Paphrag\" class=\"extiw\" title=\"en:User:Paphrag\">en:User:Paphrag</a> on August 26, 2006, <a href=\"https://creativecommons.org/licenses/by/2.5\" title=\"Creative Commons Attribution 2.5\">CC BY 2.5</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1278763\">Link</a>",
   "sizeAcres": 57179030,
   "description": "The largest island in Lake Superior is a place of isolation and wilderness. Along with its many shipwrecks, waterways, and hiking trails, the park also includes over 400 smaller islands within 4.5 miles (7.2 km) of its shores. There are only 20 mammal species on the entire island, though the relationship between its wolf and moose populations is especially unique."
 },
 {
   "parkName": "Voyageurs",
   "state": "Minnesota",
   "dateEstablished": "January 8, 1971",
   "latitude": "48.50°N",
   "longitude": "92.88°W",
   "annualVisitors": 237250,
   "websiteUrl": "https://www.nps.gov/voya/index.htm",
   "urlCode": "voya",
   "image": "assets/voyageurs.jpg",
   "imageRef": "<a href=\"https://commons.wikimedia.org/w/index.php?curid=363380\">Link</a>",
   "sizeAcres": 21820015,
   "description": "This park protecting four lakes near the Canada–US border is a site for canoeing, kayaking, and fishing. The park also preserves a history populated by Ojibwe Native Americans, French fur traders called voyageurs, and gold miners. Formed by glaciers, the region features tall bluffs, rock gardens, islands, bays, and several historic buildings."
 },
 {
   "parkName": "Gateway Arch",
   "state": "Missouri",
   "dateEstablished": "February 22, 2018",
   "latitude": "38.63°N",
   "longitude": "90.19°W",
   "annualVisitors": 1398188,
   "websiteUrl": "https://www.nps.gov/jeff/index.htm",
   "urlCode": "jeff",
   "image": "assets/gateway-arch.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Dschwen\" title=\"User:Dschwen\">Daniel Schwen</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=3468880\">Link</a>",
   "sizeAcres": 19283,
   "description": "The Gateway Arch is a 630-foot (192 m) (both high and wide) catenary arch built to commemorate the Lewis and Clark Expedition, initiated by Thomas Jefferson, and the subsequent westward expansion of the country. The nearby Old Courthouse, across a greenway to the west of the arch, was the first site of the Dred Scottcase about slavery. A museum, located in the underground visitor center below the arch, describes the arch\\'s construction and the country\\'s westward expansion."
 },
 {
   "parkName": "Glacier",
   "state": "Montana",
   "dateEstablished": "May 11, 1910",
   "latitude": "48.80°N",
   "longitude": "114.00°W",
   "annualVisitors": 3305512,
   "websiteUrl": "https://www.nps.gov/glac/index.htm",
   "urlCode": "glac",
   "image": "assets/glacier.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"http://pdphoto.org/PictureDetail.php?mat=pdef&amp;pg=8190\">pdphoto.org picture n°8190</a>Originally from <a class=\"external text\" href=\"http://fr.wikipedia.org\">fr.wikipedia</a>; description page is/was <a class=\"external text\" href=\"http://fr.wikipedia.org/w/index.php?title=Image%3AMontana5.jpg\">here</a>., Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2613534\">Link</a>",
   "sizeAcres": 101312599,
   "description": "The U.S. half of Waterton-Glacier International Peace Park, this park includes 26 glaciers and 130 named lakes surrounded by Rocky Mountain peaks. There are historic hotels and a landmark road called the Going-to-the-Sun Road in this region of rapidly receding glaciers. The local mountains, formed by an overthrust, expose Paleozoic fossils including trilobites, mollusks, giant ferns and dinosaurs."
 },
 {
   "parkName": "Great Basin",
   "state": "Nevada",
   "dateEstablished": "October 27, 1986",
   "latitude": "38.98°N",
   "longitude": "114.30°W",
   "annualVisitors": 168028,
   "websiteUrl": "https://www.nps.gov/grba/index.htm",
   "urlCode": "grba",
   "image": "assets/great-basin.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Jrbouldin\" class=\"extiw\" title=\"en:User:Jrbouldin\">James R Bouldin</a> (<a href=\"https://en.wikipedia.org/wiki/User_talk:Jrbouldin\" class=\"extiw\" title=\"en:User talk:Jrbouldin\">talk</a><span style=\"white-space:nowrap\">&nbsp;·</span> <a href=\"https://en.wikipedia.org/wiki/Special:Contributions/Jrbouldin\" class=\"extiw\" title=\"en:Special:Contributions/Jrbouldin\">contribs</a>) - Transferred from <span class=\"plainlinks\"><a class=\"external text\" href=\"//en.wikipedia.org\">en.wikipedia</a></span> to Commons by <a href=\"//commons.wikimedia.org/wiki/User:Grook_Da_Oger\" title=\"User:Grook Da Oger\">Grook Da Oger</a>., Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2615269\">Link</a>",
   "sizeAcres": 7718000,
   "description": "Based around Nevada\\'s second tallest mountain, Wheeler Peak, Great Basin National Park contains 5,000-year-old bristlecone pines, a rock glacier, and the limestone Lehman Caves. Due to its remote location, the park has some of the country\\'s darkest night skies. Wildlife includes the Townsend\\'s big-eared bat, pronghorn, and Bonneville cutthroat trout."
 },
 {
   "parkName": "Carlsbad Caverns",
   "state": "New Mexico",
   "dateEstablished": "May 14, 1930",
   "latitude": "32.17°N",
   "longitude": "104.44°W",
   "annualVisitors": 520026,
   "websiteUrl": "https://www.nps.gov/cave/index.htm",
   "urlCode": "cave",
   "image": "assets/carlsbad-caverns.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Marshman\" class=\"extiw\" title=\"w:User:Marshman\">User:Marshman</a> - Uploaded to the English Wikipedia <a class=\"external text\" href=\"https://en.wikipedia.org/w/index.php?title=Special:Undelete&amp;target=Carlsbad+Caverns+National+Park&amp;timestamp=20030814063849&amp;diff=prev\">August 2003 (deleted page)</a>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=64449\">Link</a>",
   "sizeAcres": 4676645,
   "description": "Carlsbad Caverns has 117 caves, the longest of which is over 120 miles (190 km) long. The Big Room is almost 4,000 feet (1,200 m) long, and the caves are home to over 400,000 Mexican free-tailed bats and sixteen other species. Above ground are the Chihuahuan Desert and Rattlesnake Springs."
 },
 {
   "parkName": "Theodore Roosevelt",
   "state": "North Dakota",
   "dateEstablished": "November 10, 1978",
   "latitude": "46.97°N",
   "longitude": "103.45°W",
   "annualVisitors": 708003,
   "websiteUrl": "https://www.nps.gov/thro/index.htm",
   "urlCode": "thro",
   "image": "assets/theodore-roosevelt.jpg",
   "imageRef": "<a href=\"https://commons.wikimedia.org/w/index.php?curid=114313\">Link</a>",
   "sizeAcres": 7044689,
   "description": "This region that enticed and influenced President Theodore Roosevelt consists of a park of three units in the northern badlands. Besides Roosevelt\\'s historic cabin, there are numerous scenic drives and backcountry hiking opportunities. Wildlife includes American bison, pronghorn, bighorn sheep, and wild horses."
 },
 {
   "parkName": "Cuyahoga Valley",
   "state": "Ohio",
   "dateEstablished": "October 11, 2000",
   "latitude": "41.24°N",
   "longitude": "81.55°W",
   "annualVisitors": 2226879,
   "websiteUrl": "https://www.nps.gov/cuva/index.htm",
   "urlCode": "cuva",
   "image": "assets/cuyahoga-valley.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:Niagara66&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:Niagara66 (page does not exist)\">Niagara66</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=51712984\">Link</a>",
   "sizeAcres": 3257235,
   "description": "This park along the Cuyahoga River has waterfalls, hills, trails, and exhibits on early rural living. The Ohio and Erie Canal Towpath Trail follows the Ohio and Erie Canal, where mules towed canal boats. The park has numerous historic homes, bridges, and structures, and also offers a scenic train ride."
 },
 {
   "parkName": "Crater Lake",
   "state": "Oregon",
   "dateEstablished": "May 22, 1902",
   "latitude": "42.94°N",
   "longitude": "122.1°W",
   "annualVisitors": 711749,
   "websiteUrl": "https://www.nps.gov/crla/index.htm",
   "urlCode": "crla",
   "image": "assets/crater-lake.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:Zainubrazvi&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:Zainubrazvi (page does not exist)\">Zainubrazvi</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2033872\">Link</a>",
   "sizeAcres": 18322405,
   "description": "Crater Lake lies in the caldera of an ancient volcano called Mount Mazama that collapsed 7,700 years ago. The lake is the deepest in the United States and is noted for its vivid blue color and water clarity. Wizard Island and the Phantom Ship are more recent volcanic formations within the caldera. As the lake has no inlets or outlets, the lake is replenished only by precipitation."
 },
 {
   "parkName": "Congaree",
   "state": "South Carolina",
   "dateEstablished": "November 10, 2003",
   "latitude": "33.78°N",
   "longitude": "80.78°W",
   "annualVisitors": 159595,
   "websiteUrl": "https://www.nps.gov/cong/index.htm",
   "urlCode": "cong",
   "image": "assets/conagree.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/people/77660923@N08\">Congaree National Park</a> from Hopkins, SC, USA - <a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/photos/congareenps/7166139814/\">Flickr</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=44362467\">Link</a>",
   "sizeAcres": 2653922,
   "description": "On the Congaree River, this park is the largest portion of old-growthfloodplain forest left in North America. Some of the trees are the tallest in the eastern United States. An elevated walkway called the Boardwalk Loop guides visitors through the swamp."
 },
 {
   "parkName": "Badlands",
   "state": "South Dakota",
   "dateEstablished": "November 10, 1978",
   "latitude": "43.75°N",
   "longitude": "102.50°W",
   "annualVisitors": 1054325,
   "websiteUrl": "https://www.nps.gov/badl/index.htm",
   "urlCode": "badl",
   "image": "assets/badlands.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Jsoo1\" class=\"extiw\" title=\"en:User:Jsoo1\">Jsoo1</a> at the <a href=\"https://en.wikipedia.org/wiki/\" class=\"extiw\" title=\"w:\">English language Wikipedia</a>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=14612841\">Link</a>",
   "sizeAcres": 24275594,
   "description": "The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies. The White River Badlands contain the largest assemblage of known late Eocene and Oligocene mammal fossils. The wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs."
 },
 {
   "parkName": "Wind Cave",
   "state": "South Dakota",
   "dateEstablished": "January 9, 1903",
   "latitude": "43.57°N",
   "longitude": "103.48°W",
   "annualVisitors": 619924,
   "websiteUrl": "https://www.nps.gov/wica/index.htm",
   "urlCode": "wica",
   "image": "assets/wind-cave.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Dave_Bunnell\" title=\"User:Dave Bunnell\">Dave Bunnell / Under Earth Images</a> - original work of uploader, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=7782810\">Link</a>",
   "sizeAcres": 3397084,
   "description": "Wind Cave is distinctive for its calcite fin formations called boxwork, a unique formation rarely found elsewhere, and needle-like growths called frostwork. The cave is one of the longest and most complex caves in the world. Above ground is a mixed-grass prairie with animals such as bison, black-footed ferrets, and prairie dogs, and ponderosa pine forests that are home to cougars and elk. The cave is culturally significant to the Lakota people as the site \\\"from which Wakan Tanka, the Great Mystery, sent the buffalo out into their hunting grounds.\\\""
 },
 {
   "parkName": "Big Bend",
   "state": "Texas",
   "dateEstablished": "June 12, 1944",
   "latitude": "29.25°N",
   "longitude": "103.25°W",
   "annualVisitors": 440276,
   "websiteUrl": "https://www.nps.gov/bibe/index.htm",
   "urlCode": "bibe",
   "image": "assets/big-bend.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"http://www.nps.gov/storage/images/\">National Park Service Digital Image Archives</a> - <a rel=\"nofollow\" class=\"external free\" href=\"http://www.nps.gov/storage/images/bibe/Webpages/originals/412.JPG\">http://www.nps.gov/storage/images/bibe/Webpages/originals/412.JPG</a>Gallery <a rel=\"nofollow\" class=\"external free\" href=\"http://www.nps.gov/storage/images/bibe/Webpages/index.html\">http://www.nps.gov/storage/images/bibe/Webpages/index.html</a>Transferred to Commons by <a href=\"//commons.wikimedia.org/wiki/User:F%C3%A6\" title=\"User:Fæ\">Fæ</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=24123258\">Link</a>",
   "sizeAcres": 80116321,
   "description": "Named for the prominent bend in the Rio Grande along the U.S.–Mexico border, this park encompasses a large and remote part of the Chihuahuan Desert. Its main attraction is backcountry recreation in the arid Chisos Mountains and in canyons along the river. A wide variety of Cretaceous and Tertiary fossils as well as cultural artifacts of Native Americans also exist within its borders."
 },
 {
   "parkName": "Guadalupe Mountains",
   "state": "Texas",
   "dateEstablished": "October 15, 1966",
   "latitude": "31.92°N",
   "longitude": "104.87°W",
   "annualVisitors": 225257,
   "websiteUrl": "https://www.nps.gov/gumo/index.htm",
   "urlCode": "gumo",
   "image": "assets/guadalupe-mtns.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Leaflet\" title=\"User:Leaflet\">Leaflet</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=4550001\">Link</a>",
   "sizeAcres": 8636710,
   "description": "This park contains Guadalupe Peak, the highest point in Texas, as well as the scenic McKittrick Canyon filled with bigtooth maples, a corner of the arid Chihuahuan Desert, and a fossilized coral reef from the Permian era."
 },
 {
   "parkName": "Virgin Islands",
   "state": "U.S. Virgin Islands",
   "dateEstablished": "August 2, 1956",
   "latitude": "18.33°N",
   "longitude": "64.73°W",
   "annualVisitors": 304408,
   "websiteUrl": "https://www.nps.gov/viis/index.htm",
   "urlCode": "viis",
   "image": "assets/virgin-islands.jpg",
   "imageRef": "<a href=\"https://en.wikipedia.org/wiki/User:Fred_Hsu\" class=\"extiw\" title=\"wikipedia:User:Fred Hsu\">Wikipedia:User:Fred Hsu</a> on <a class=\"external text\" href=\"http://en.wikipedia.org\">en.wikipedia</a>) - Photo taken and uploaded by user, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=6882523\">Link</a>",
   "sizeAcres": 1494000,
   "description": "This island park on Saint John preserves Taíno archaeological sites and the ruins of sugar plantations from Columbus\\'s time, as well as all the natural environs. Surrounding the pristine beaches are mangrove forests, seagrass beds, and coral reefs."
 },
 {
   "parkName": "Arches",
   "state": "Utah",
   "dateEstablished": "November 12, 1971",
   "latitude": "38.68°N",
   "longitude": "109.57°W",
   "annualVisitors": 1539028,
   "websiteUrl": "https://www.nps.gov/arch/index.htm",
   "urlCode": "arch",
   "image": "assets/arches.jpg",
   "imageRef": "<a href=\"https://commons.wikimedia.org/w/index.php?curid=1340592\">Link</a>",
   "sizeAcres": 7667898,
   "description": "This site features more than 2,000 natural sandstone arches, with some of the most popular arches in the park being Delicate Arch, Landscape Arch and Double Arch. Millions of years of erosion have created these structures located in a desert climate where the arid ground has life-sustaining biological soil crusts and potholes that serve as natural water-collecting basins. Other geologic formations include stone pinnacles, fins, and balancing rocks."
 },
 {
   "parkName": "Bryce Canyon",
   "state": "Utah",
   "dateEstablished": "February 25, 1928",
   "latitude": "37.57°N",
   "longitude": "112.18°W",
   "annualVisitors": 2571684,
   "websiteUrl": "https://www.nps.gov/brca/index.htm",
   "urlCode": "brca",
   "image": "assets/bryce-canyon.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Digon3\" title=\"User:Digon3\">Jonathan Zander</a>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1188661\">Link</a>",
   "sizeAcres": 3583508,
   "description": "Bryce Canyon is a geological amphitheater on the Paunsaugunt Plateau with hundreds of tall, multicolored sandstone hoodoos formed by erosion. The region was originally settled by Native Americans and later by Mormon pioneers."
 },
 {
   "parkName": "Canyonlands",
   "state": "Utah",
   "dateEstablished": "September 12, 1964",
   "latitude": "38.2°N",
   "longitude": "109.93°W",
   "annualVisitors": 742271,
   "websiteUrl": "https://www.nps.gov/cany/index.htm",
   "urlCode": "cany",
   "image": "assets/canyonlands.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/people/61456446@N06\">Murray Foubister</a> - <a rel=\"nofollow\" class=\"external free\" href=\"https://www.flickr.com/photos/mfoubister/6294480744/\">https://www.flickr.com/photos/mfoubister/6294480744/</a>, <a href=\"https://creativecommons.org/licenses/by-sa/2.0\" title=\"Creative Commons Attribution-Share Alike 2.0\">CC BY-SA 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=51853455\">Link</a>",
   "sizeAcres": 33759783,
   "description": "This landscape was eroded into a maze of canyons, buttes, and mesas by the combined efforts of the Colorado River, Green River, and their tributaries, which divide the park into three districts. The park also contains rock pinnacles and arches, as well as artifacts from Ancient Pueblo peoples."
 },
 {
   "parkName": "Capitol Reef",
   "state": "Utah",
   "dateEstablished": "December 18, 1971",
   "latitude": "38.20°N",
   "longitude": "111.17°W",
   "annualVisitors": 1150165,
   "websiteUrl": "https://www.nps.gov/care/index.htm",
   "urlCode": "care",
   "image": "assets/capitol-reef.jpeg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Bigtimepeace\" title=\"User:Bigtimepeace\">Bigtimepeace</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=7342151\">Link</a>",
   "sizeAcres": 24190450,
   "description": "The park\\'s Waterpocket Fold is a 100-mile (160 km) monocline that exhibits the earth\\'s diverse geologic layers. Other natural features include monoliths, cliffs, and sandstone domes shaped like the United States Capitol."
 },
 {
   "parkName": "Zion",
   "state": "Utah",
   "dateEstablished": "November 19, 1919",
   "latitude": "37.30°N",
   "longitude": "113.05°W",
   "annualVisitors": 4504812,
   "websiteUrl": "https://www.nps.gov/zion/index.htm",
   "urlCode": "zion",
   "image": "assets/zion.jpg",
   "imageRef": "<span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"https://creativecommons.org/licenses/by-sa/4.0\" title=\"Creative Commons Attribution-Share Alike 4.0\">CC BY-SA 4.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=3064925\">Link</a>",
   "sizeAcres": 14723702,
   "description": "Located at the junction of the Colorado Plateau, Great Basin, and Mojave Desert, this park contains sandstone features such as mesas, rock towers, and canyons, including the Virgin River Narrows. The various sandstone formations and the forks of the Virgin River create a wilderness divided into four ecosystems: desert, riparian, woodland, and coniferous forest."
 },
 {
   "parkName": "Shenandoah",
   "state": "Virginia",
   "dateEstablished": "December 26, 1935",
   "latitude": "38.53°N",
   "longitude": "78.35°W",
   "annualVisitors": 1458874,
   "websiteUrl": "https://www.nps.gov/shen/index.htm",
   "urlCode": "shen",
   "image": "assets/shenandoah.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/people/67015038@N06\">Shenandoah National Park</a> from Virginia - <a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/photos/snpphotos/22028259442/\">Early Fall at Dark Hollow Falls</a>, Public Domain, <a href=\"https://commons.wikimedia.org/w/index.php?curid=45094938\">Link</a>",
   "sizeAcres": 19921777,
   "description": "Shenandoah\\'s Blue Ridge Mountains are covered by hardwood forests that teem with a wide variety of wildlife. The Skyline Drive and Appalachian Trail run the entire length of this narrow park, along with more than 500 miles (800 km) of hiking trails passing scenic overlooks and cataracts of the Shenandoah River."
 },
 {
   "parkName": "Mount Rainier",
   "state": "Washington",
   "dateEstablished": "March 2, 1899",
   "latitude": "46.85°N",
   "longitude": "121.75°W",
   "annualVisitors": 1415867,
   "websiteUrl": "https://www.nps.gov/mora/index.htm",
   "urlCode": "mora",
   "image": "assets/mount-rainier.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Stan_Shebs\" title=\"User:Stan Shebs\">Stan Shebs</a>, <a href=\"https://creativecommons.org/licenses/by-sa/3.0\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=278794\">Link</a>",
   "sizeAcres": 23638164,
   "description": "Mount Rainier, an active stratovolcano, is the most prominent peak in the Cascades and is covered by 26 named glaciers including Carbon Glacier and Emmons Glacier, the largest in the contiguous United States. The mountain is popular for climbing, and more than half of the park is covered by subalpine and alpine forests and meadows seasonally in bloom with wildflowers. Paradise on the south slope is the snowiest place on Earth where snowfall is measured regularly. The Longmire visitor center is the start of the Wonderland Trail, which encircles the mountain."
 },
 {
   "parkName": "North Cascades",
   "state": "Washington",
   "dateEstablished": "October 2, 1968",
   "latitude": "48.70°N",
   "longitude": "121.20°W",
   "annualVisitors":3032,
   "websiteUrl": "https://www.nps.gov/noca/index.htm",
   "urlCode": "noca",
   "image": "assets/north-cascades.jpg",
   "imageRef": "<a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/photos/75525471@N00\">Daniel Hershman</a> - <a rel=\"nofollow\" class=\"external text\" href=\"https://www.flickr.com/photos/75525471@N00/497448265\">Flickr</a>, <a href=\"https://creativecommons.org/licenses/by/2.0\" title=\"Creative Commons Attribution 2.0\">CC BY 2.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=2752656\">Link</a>",
   "sizeAcres":5047809,
   "description": "This complex includes two geographically distinct units of the national park, as well as Ross Lake and Lake Chelan National Recreation Areas. The highly glaciated mountains are spectacular examples of Cascade geology. Popular hiking and climbing areas include Cascade Pass, Mount Shuksan, Mount Triumph, and Eldorado Peak."
 },
 {
   "parkName": "Olympic",
   "state": "Washington",
   "dateEstablished": "June 29, 1938",
   "latitude": "47.97°N",
   "longitude": "123.50°W",
   "annualVisitors": 3401996,
   "websiteUrl": "https://www.nps.gov/olym/index.htm",
   "urlCode": "olym",
   "image": "assets/olympic.jpg",
   "imageRef": "<a href=\"//commons.wikimedia.org/w/index.php?title=User:KevinM~commonswiki&amp;action=edit&amp;redlink=1\" class=\"new\" title=\"User:KevinM~commonswiki (page does not exist)\">KevinM~commonswiki</a> assumed (based on copyright claims). - No machine-readable source provided. Own work assumed (based on copyright claims)., <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1029413\">Link</a>",
   "sizeAcres": 92264941,
   "description": "Situated on the Olympic Peninsula, this park includes a wide range of ecosystems from Pacific shoreline to temperate rainforests to the alpine slopes of the Olympic Mountains, the tallest of which is Mount Olympus. The Hoh Rainforest and Quinault Rainforest are the wettest area in the contiguous United States, with the Hoh receiving an average of almost 12 ft (3.7 m) of rain every year."
 },
 {
   "parkName": "Grand Teton",
   "state": "Wyoming",
   "dateEstablished": "February 26, 1929",
   "latitude": "43.73°N",
   "longitude": "110.80°W",
   "annualVisitors": 3317000,
   "websiteUrl": "https://www.nps.gov/grte/index.htm",
   "urlCode": "grte",
   "image": "assets/grand-teton.jpeg",
   "imageRef": "<a href=\"//commons.wikimedia.org/wiki/User:Maveric149\" class=\"mw-redirect\" title=\"User:Maveric149\">Daniel Mayer</a> - <span class=\"int-own-work\" lang=\"en\">Own work</span>, <a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" title=\"Creative Commons Attribution-Share Alike 3.0\">CC BY-SA 3.0</a>, <a href=\"https://commons.wikimedia.org/w/index.php?curid=1848111\">Link</a>",
   "sizeAcres": 31004422,
   "description": "Grand Teton is the tallest mountain in the Teton Range. The park\\'s historic Jackson Hole and reflective piedmont lakes teem with endemic wildlife, with a backdrop of craggy mountains that rise abruptly from the sage-covered valley."
 }
];

const states = {
   "Alabama": {
      "abbreviation": "AL",
      "capitalCity": "Montgomery",
      "dateEstablished": "Dec 14, 1819",
      "Population": 4874747,
      "totalAreaMi2": 52420,
      "totalLandAreaMi2": 50645,
      "totalWaterAreaMi2": 1775,
      "nationalParks": []
   },
   "Alaska": {
      "abbreviation": "AK",
      "capitalCity": "Juneau",
      "dateEstablished": "Jan 3, 1959",
      "Population": 739795,
      "totalAreaMi2": 665384,
      "totalLandAreaMi2": 570641,
      "totalWaterAreaMi2": 94743,
      "nationalParks": ["Denali", "Gates of the Arctic", "Glacier Bay", "Katmai", "Kenai Fjords", "Kobuk Valley", "Lake Clark", "Wrangell - St. Elias"]
   },
   "Arizona": {
      "abbreviation": "AZ",
      "capitalCity": "Phoenix",
      "dateEstablished": "Feb 14, 1912",
      "Population": 7016270,
      "totalAreaMi2": 113990,
      "totalLandAreaMi2": 113594,
      "totalWaterAreaMi2": 396,
      "nationalParks": ["Grand Canyon", "Petrified Forest", "Saguaro"]
   },
   "Arkansas": {
      "abbreviation": "AR",
      "capitalCity": "Little Rock",
      "dateEstablished": "Jun 15, 1836",
      "Population": 3004279,
      "totalAreaMi2": 53179,
      "totalLandAreaMi2": 52035,
      "totalWaterAreaMi2": 1143,
      "nationalParks": ["Hot Springs"]
   },
   "California": {
      "abbreviation": "CA",
      "capitalCity": "Sacramento",
      "dateEstablished": "Sep 9, 1850",
      "Population": 39536653,
      "totalAreaMi2": 163695,
      "totalLandAreaMi2": 155779,
      "totalWaterAreaMi2": 7916,
      "nationalParks": ["Channel Islands", "Death Valley", "Joshua Tree", "Kings Canyon", "Lassen Volcanic", "Pinnacles", "Redwood", "Sequoia", "Yosemite"]
   },
   "Colorado": {
      "abbreviation": "CO",
      "capitalCity": "Denver",
      "dateEstablished": "Aug 1, 1876",
      "Population": 5607154,
      "totalAreaMi2": 104094,
      "totalLandAreaMi2": 103642,
      "totalWaterAreaMi2": 452,
      "nationalParks": ["Black Canyon of the Gunnison", "Great Sand Dunes", "Mesa Verde" ,"Rocky Mountain"]
   },
   "Connecticut": {
      "abbreviation": "CT",
      "capitalCity": "Hartford",
      "dateEstablished": "Jan 9, 1788",
      "Population": 3588184,
      "totalAreaMi2": 5543,
      "totalLandAreaMi2": 4842,
      "totalWaterAreaMi2": 701,
      "nationalParks": []
   },
   "Delaware": {
      "abbreviation": "DE",
      "capitalCity": "Dover",
      "dateEstablished": "Dec 7, 1787",
      "Population": 961939,
      "totalAreaMi2": 2489,
      "totalLandAreaMi2": 1949,
      "totalWaterAreaMi2": 540,
      "nationalParks": []
   },
   "Florida": {
      "abbreviation": "FL",
      "capitalCity": "Tallahassee",
      "dateEstablished": "Mar 3, 1845",
      "Population": 20984400,
      "totalAreaMi2": 65758,
      "totalLandAreaMi2": 53625,
      "totalWaterAreaMi2": 12133,
      "nationalParks": ["Biscayne", "Dry Tortugas", "Everglades"]
   },
   "Georgia": {
      "abbreviation": "GA",
      "capitalCity": "Atlanta",
      "dateEstablished": "Jan 2, 1788",
      "Population": 10429379,
      "totalAreaMi2": 59425,
      "totalLandAreaMi2": 57513,
      "totalWaterAreaMi2": 1912,
      "nationalParks": []
   },
   "Hawaii": {
      "abbreviation": "HI",
      "capitalCity": "Honolulu",
      "dateEstablished": "Aug 21, 1959",
      "Population": 1427538,
      "totalAreaMi2": 10932,
      "totalLandAreaMi2": 6423,
      "totalWaterAreaMi2": 4509,
      "nationalParks": ["Haleakala", "Hawaii Volcanoes"]
   },
   "Idaho": {
      "abbreviation": "ID",
      "capitalCity": "Boise",
      "dateEstablished": "Jul 3, 1890",
      "Population": 1716943,
      "totalAreaMi2": 83569,
      "totalLandAreaMi2": 82643,
      "totalWaterAreaMi2": 926,
      "nationalParks": ["Yellowstone"]
   },
   "Illinois": {
      "abbreviation": "IL",
      "capitalCity": "Springfield",
      "dateEstablished": "Dec 3, 1818",
      "Population": 12802023,
      "totalAreaMi2": 57914,
      "totalLandAreaMi2": 55519,
      "totalWaterAreaMi2": 2395,
      "nationalParks": []
   },
   "Indiana": {
      "abbreviation": "IN",
      "capitalCity": "Indianapolis",
      "dateEstablished": "Dec 11, 1816",
      "Population": 6666818,
      "totalAreaMi2": 36420,
      "totalLandAreaMi2": 35826,
      "totalWaterAreaMi2": 593,
      "nationalParks": []
   },
   "Iowa": {
      "abbreviation": "IA",
      "capitalCity": "Des Moines",
      "dateEstablished": "Dec 28, 1846",
      "Population": 3145711,
      "totalAreaMi2": 56273,
      "totalLandAreaMi2": 55857,
      "totalWaterAreaMi2": 416,
      "nationalParks": []
   },
   "Kansas": {
      "abbreviation": "KS",
      "capitalCity": "Topeka",
      "dateEstablished": "Jan 29, 1861",
      "Population": 2913123,
      "totalAreaMi2": 82278,
      "totalLandAreaMi2": 81759,
      "totalWaterAreaMi2": 520,
      "nationalParks": []
   },
   "Kentucky": {
      "abbreviation": "KY",
      "capitalCity": "Frankfort",
      "dateEstablished": "Jun 1, 1792",
      "Population": 4454189,
      "totalAreaMi2": 40408,
      "totalLandAreaMi2": 39486,
      "totalWaterAreaMi2": 921,
      "nationalParks": ["Mammoth Cave"]
   },
   "Louisiana": {
      "abbreviation": "LA",
      "capitalCity": "Baton Rouge",
      "dateEstablished": "Apr 30, 1812",
      "Population": 4684333,
      "totalAreaMi2": 52378,
      "totalLandAreaMi2": 43204,
      "totalWaterAreaMi2": 9174,
      "nationalParks": []
   },
   "Maine": {
      "abbreviation": "ME",
      "capitalCity": "Augusta",
      "dateEstablished": "Mar 15, 1820",
      "Population": 1335907,
      "totalAreaMi2": 35380,
      "totalLandAreaMi2": 30843,
      "totalWaterAreaMi2": 4537,
      "nationalParks": ["Acadia"]
   },
   "Maryland": {
      "abbreviation": "MD",
      "capitalCity": "Annapolis",
      "dateEstablished": "Apr 28, 1788",
      "Population": 6052177,
      "totalAreaMi2": 12406,
      "totalLandAreaMi2": 9707,
      "totalWaterAreaMi2": 2699,
      "nationalParks": []
   },
   "Massachusetts": {
      "abbreviation": "MA",
      "capitalCity": "Boston",
      "dateEstablished": "Feb 6, 1788",
      "Population": 6859819,
      "totalAreaMi2": 10554,
      "totalLandAreaMi2": 7800,
      "totalWaterAreaMi2": 2754,
      "nationalParks": []
   },
   "Michigan": {
      "abbreviation": "MI",
      "capitalCity": "Lansing",
      "dateEstablished": "Jan 26, 1837",
      "Population": 9962311,
      "totalAreaMi2": 96714,
      "totalLandAreaMi2": 56539,
      "totalWaterAreaMi2": 40175,
      "nationalParks": ["Isle Royale"]
   },
   "Minnesota": {
      "abbreviation": "MN",
      "capitalCity": "St. Paul",
      "dateEstablished": "May 11, 1858",
      "Population": 5576606,
      "totalAreaMi2": 86936,
      "totalLandAreaMi2": 79627,
      "totalWaterAreaMi2": 7309,
      "nationalParks": ["Voyageurs"]
   },
   "Mississippi": {
      "abbreviation": "MS",
      "capitalCity": "Jackson",
      "dateEstablished": "Dec 10, 1817",
      "Population": 2984100,
      "totalAreaMi2": 48432,
      "totalLandAreaMi2": 46923,
      "totalWaterAreaMi2": 1508,
      "nationalParks": []
   },
   "Missouri": {
      "abbreviation": "MO",
      "capitalCity": "Jefferson City",
      "dateEstablished": "Aug 10, 1821",
      "Population": 6113532,
      "totalAreaMi2": 69707,
      "totalLandAreaMi2": 68742,
      "totalWaterAreaMi2": 965,
      "nationalParks": ["Gateway Arch"]
   },
   "Montana": {
      "abbreviation": "MT",
      "capitalCity": "Helena",
      "dateEstablished": "Nov 8, 1889",
      "Population": 1050493,
      "totalAreaMi2": 147040,
      "totalLandAreaMi2": 145546,
      "totalWaterAreaMi2": 1494,
      "nationalParks": ["Glacier", "Yellowstone"]
   },
   "Nebraska": {
      "abbreviation": "NE",
      "capitalCity": "Lincoln",
      "dateEstablished": "Mar 1, 1867",
      "Population": 1920076,
      "totalAreaMi2": 77348,
      "totalLandAreaMi2": 76824,
      "totalWaterAreaMi2": 524,
      "nationalParks": []
   },
   "Nevada": {
      "abbreviation": "NV",
      "capitalCity": "Carson City",
      "dateEstablished": "Oct 31, 1864",
      "Population": 2998039,
      "totalAreaMi2": 110572,
      "totalLandAreaMi2": 109781,
      "totalWaterAreaMi2": 791,
      "nationalParks": ["Death Valley", "Great Basin"]
   },
   "New Hampshire": {
      "abbreviation": "NH",
      "capitalCity": "Concord",
      "dateEstablished": "Jun 21, 1788",
      "Population": 1342795,
      "totalAreaMi2": 9349,
      "totalLandAreaMi2": 8953,
      "totalWaterAreaMi2": 397,
      "nationalParks": []
   },
   "New Jersey": {
      "abbreviation": "NJ",
      "capitalCity": "Trenton",
      "dateEstablished": "Dec 18, 1787",
      "Population": 9005644,
      "totalAreaMi2": 8723,
      "totalLandAreaMi2": 7354,
      "totalWaterAreaMi2": 1368,
      "nationalParks": []
   },
   "New Mexico": {
      "abbreviation": "NM",
      "capitalCity": "Santa Fe",
      "dateEstablished": "Jan 6, 1912",
      "Population": 2088070,
      "totalAreaMi2": 121590,
      "totalLandAreaMi2": 121298,
      "totalWaterAreaMi2": 292,
      "nationalParks": ["Carlsbad Caverns"]
   },
   "New York": {
      "abbreviation": "NY",
      "capitalCity": "Albany",
      "dateEstablished": "Jul 26, 1788",
      "Population": 19849399,
      "totalAreaMi2": 54555,
      "totalLandAreaMi2": 47126,
      "totalWaterAreaMi2": 7429,
      "nationalParks": []
   },
   "North Carolina": {
      "abbreviation": "NC",
      "capitalCity": "Raleigh",
      "dateEstablished": "Nov 21, 1789",
      "Population": 10273419,
      "totalAreaMi2": 53819,
      "totalLandAreaMi2": 48618,
      "totalWaterAreaMi2": 5201,
      "nationalParks": ["Great Smoky Mountains"]
   },
   "North Dakota": {
      "abbreviation": "ND",
      "capitalCity": "Bismarck",
      "dateEstablished": "Nov 2, 1889",
      "Population": 755393,
      "totalAreaMi2": 70698,
      "totalLandAreaMi2": 69001,
      "totalWaterAreaMi2": 1698,
      "nationalParks": ["Theodore Roosevelt"]
   },
   "Ohio": {
      "abbreviation": "OH",
      "capitalCity": "Columbus",
      "dateEstablished": "Mar 1, 1803",
      "Population": 11658609,
      "totalAreaMi2": 44826,
      "totalLandAreaMi2": 40861,
      "totalWaterAreaMi2": 3965,
      "nationalParks": ["Cuyahoga Valley"]
   },
   "Oklahoma": {
      "abbreviation": "OK",
      "capitalCity": "Oklahoma City",
      "dateEstablished": "Nov 16, 1907",
      "Population": 3930864,
      "totalAreaMi2": 69899,
      "totalLandAreaMi2": 68595,
      "totalWaterAreaMi2": 1304,
      "nationalParks": []
   },
   "Oregon": {
      "abbreviation": "OR",
      "capitalCity": "Salem",
      "dateEstablished": "Feb 14, 1859",
      "Population": 4142776,
      "totalAreaMi2": 98379,
      "totalLandAreaMi2": 95988,
      "totalWaterAreaMi2": 2391,
      "nationalParks": ["Crater Lake"]
   },
   "Pennsylvania": {
      "abbreviation": "PA",
      "capitalCity": "Harrisburg",
      "dateEstablished": "Dec 12, 1787",
      "Population": 12805537,
      "totalAreaMi2": 46054,
      "totalLandAreaMi2": 44743,
      "totalWaterAreaMi2": 1312,
      "nationalParks": []
   },
   "Rhode Island": {
      "abbreviation": "RI",
      "capitalCity": "Providence",
      "dateEstablished": "May 29, 1790",
      "Population": 1059639,
      "totalAreaMi2": 1545,
      "totalLandAreaMi2": 1034,
      "totalWaterAreaMi2": 511,
      "nationalParks": []
   },
   "South Carolina": {
      "abbreviation": "SC",
      "capitalCity": "Columbia",
      "dateEstablished": "May 23, 1788",
      "Population": 5024369,
      "totalAreaMi2": 32020,
      "totalLandAreaMi2": 30061,
      "totalWaterAreaMi2": 1960,
      "nationalParks": ["Conagree"]
   },
   "South Dakota": {
      "abbreviation": "SD",
      "capitalCity": "Pierre",
      "dateEstablished": "Nov 2, 1889",
      "Population": 869666,
      "totalAreaMi2": 77116,
      "totalLandAreaMi2": 75811,
      "totalWaterAreaMi2": 1305,
      "nationalParks": ["Badlands", "Wind Cave"]
   },
   "Tennessee": {
      "abbreviation": "TN",
      "capitalCity": "Nashville",
      "dateEstablished": "Jun 1, 1796",
      "Population": 6715984,
      "totalAreaMi2": 42144,
      "totalLandAreaMi2": 41235,
      "totalWaterAreaMi2": 909,
      "nationalParks": ["Great Smoky Mountains"]
   },
   "Texas": {
      "abbreviation": "TX",
      "capitalCity": "Austin",
      "dateEstablished": "Dec 29, 1845",
      "Population": 28304596,
      "totalAreaMi2": 268596,
      "totalLandAreaMi2": 261232,
      "totalWaterAreaMi2": 7365,
      "nationalParks": ["Big Bend", "Guadalupe Mountains"]
   },
   "Utah": {
      "abbreviation": "UT",
      "capitalCity": "Salt Lake City",
      "dateEstablished": "Jan 4, 1896",
      "Population": 3101833,
      "totalAreaMi2": 84897,
      "totalLandAreaMi2": 82170,
      "totalWaterAreaMi2": 2727,
      "nationalParks": ["Arches", "Bryce Canyon", "Canyonlands", "Capitol Reef", "Zion"]
   },
   "Vermont": {
      "abbreviation": "VT",
      "capitalCity": "Montpelier",
      "dateEstablished": "Mar 4, 1791",
      "Population": 623657,
      "totalAreaMi2": 9616,
      "totalLandAreaMi2": 9217,
      "totalWaterAreaMi2": 400,
      "nationalParks": []
   },
   "Virginia": {
      "abbreviation": "VA",
      "capitalCity": "Richmond",
      "dateEstablished": "Jun 25, 1788",
      "Population": 8470020,
      "totalAreaMi2": 42775,
      "totalLandAreaMi2": 39490,
      "totalWaterAreaMi2": 3285,
      "nationalParks": ["Shenandoah"]
   },
   "Washington": {
      "abbreviation": "WA",
      "capitalCity": "Olympia",
      "dateEstablished": "Nov 11, 1889",
      "Population": 7405743,
      "totalAreaMi2": 71298,
      "totalLandAreaMi2": 66456,
      "totalWaterAreaMi2": 4842,
      "nationalParks": ["Mount Rainier", "North Cascades", "Olympic"]
   },
   "West Virginia": {
      "abbreviation": "WV",
      "capitalCity": "Charleston",
      "dateEstablished": "Jun 20, 1863",
      "Population": 1815857,
      "totalAreaMi2": 24230,
      "totalLandAreaMi2": 24038,
      "totalWaterAreaMi2": 192,
      "nationalParks": []
   },
   "Wisconsin": {
      "abbreviation": "WI",
      "capitalCity": "Madison",
      "dateEstablished": "May 29, 1848",
      "Population": 5795483,
      "totalAreaMi2": 65496,
      "totalLandAreaMi2": 54158,
      "totalWaterAreaMi2": 11339,
      "nationalParks": []
   },
   "Wyoming": {
      "abbreviation": "WY",
      "capitalCity": "Cheyenne",
      "dateEstablished": "Jul 10, 1890",
      "Population": 579315,
      "totalAreaMi2": 97813,
      "totalLandAreaMi2": 97093,
      "totalWaterAreaMi2": 720,
      "nationalParks": ["Grand Teton", "Yellowstone"]
   },
   "American Samoa": {
      "abbreviation": "AS",
      "capitalCity": "Pago Pago",
      "dateEstablished": 1900,
      "Population": 57400,
      "totalAreaMi2": 581,
      "totalLandAreaMi2": 76,
      "totalWaterAreaMi2": 505,
      "nationalParks": ["American Samoa"]
   },
   "U.S. Virgin Islands": {
      "abbreviation": "VI",
      "capitalCity": "Charlotte Amalie",
      "dateEstablished": 1917,
      "Population": 103700,
      "totalAreaMi2": 733,
      "totalLandAreaMi2": 134,
      "totalWaterAreaMi2": 599,
      "nationalParks": ["Virgin Islands"]
   },
   "District of Columbia": {
      "abbreviation": "DC",
      "capitalCity": null,
      "dateEstablished": "Jul 16, 1790",
      "Population": 693972,
      "totalAreaMi2": 68,
      "totalLandAreaMi2": 61,
      "totalWaterAreaMi2": 7,
      "nationalParks": []
   },
   "Guam": {
      "abbreviation": "GU",
      "capitalCity": "Hagatna",
      "dateEstablished": 1899,
      "Population": 161700,
      "totalAreaMi2": 571,
      "totalLandAreaMi2": 210,
      "totalWaterAreaMi2": 361,
      "nationalParks": []
   },
   "Northern Mariana Islands": {
      "abbreviation": "MP",
      "capitalCity": "Saipan",
      "dateEstablished": 1986,
      "Population": 52300,
      "totalAreaMi2": 1976,
      "totalLandAreaMi2": 182,
      "totalWaterAreaMi2": 1793,
      "nationalParks": []
   },
   "Puerto Rico": {
      "abbreviation": "PR",
      "capitalCity": "San Juan",
      "dateEstablished": 1899,
      "Population": 3337177,
      "totalAreaMi2": 5325,
      "totalLandAreaMi2": 3424,
      "totalWaterAreaMi2": 1901,
      "nationalParks": []
   }
};

module.exports = {
  nationalParks,
  states
}